spring:
    profiles:
        active:
        - dev
---
spring:
    profiles:dev
    application:
        name:spring-cloud-learn-dev
---
spring:
    profiles:dev
    application:
        name:spring-cloud-learn-test